colors:
  red: "#cc241d"
  green: "#98971a"
  yellow: "#d79921"
  blue: "#458588"
  purple: "#b16286"
  aqua: "#689d6a"
  orange: "#d65d0e"
  dark_red: "#9d0006"
  dark_green: "#79740e"
  dark_yellow: "#b57614"
  dark_blue: "#076678"
  dark_purple: "#8f3f71"
  dark_aqua: "#427b58"
  dark_orange: "#af3a03"
  light_red: "#fb4934"
  light_green: "#b8bb26"
  light_yellow: "#fabd2f"
  light_blue: "#83a598"
  light_purple: "#d3869b"
  light_aqua: "#8ec07c"
  light_orange: "#fe8019"
  white: "#ebdbb2"
  light_gray: "#a89984"
  gray: "#a89984"
  dark_gray: "#928374"
  very_dark_gray: "#3c3836"
  black: "#282828"

tool_colors:
  - "white"
  - "red"
  - "green"
  - "yellow"
  - "blue"
  - "purple"
  - "aqua"
  - "orange"

background_color: "black"
faint_background_color: "very_dark_gray"
extreme_background_color: "dark_gray"

grid_color: "dark_gray"
intersection_color: "light_yellow"
point_color: "light_red"
guide_color: "gray"
text_color: "white"
